name: update-hpai-cases

on:
  workflow_dispatch:
  schedule:
    # every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: microsoft/playwright-github-action@v1

      - name: Scrape HPAI cases from Tableau
        id: scraper
        run: |
          npm i
          echo "::set-output name=url::$(npx ts-node ./scripts/playwright.ts)"

      - name: Call the /api/update endpoint
        run: |
          curl -X POST \ 
          --url '${{ secrets.UPDATE_ENDPOINT }}' \
          -h 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}' \
          -d '{ url: ${{ steps.scraper.outputs.url }}, shouldNotify: ${{ secrets.SHOULD_NOTIFY }} }'
